apiVersion: v1
kind: Service
metadata:
  name: hotel-management-service
spec:
  type: NodePort
  selector:
    app: hotel-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
